using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class LobbySpotModel
{
    [RealtimeProperty(1, true, true)]
    bool _occupied;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class LobbySpotModel : RealtimeModel {
    public bool occupied {
        get {
            return _occupiedProperty.value;
        }
        set {
            if (_occupiedProperty.value == value) return;
            _occupiedProperty.value = value;
            InvalidateReliableLength();
            FireOccupiedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(LobbySpotModel model, T value);
    public event PropertyChangedHandler<bool> occupiedDidChange;
    
    public enum PropertyID : uint {
        Occupied = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _occupiedProperty;
    
    #endregion
    
    public LobbySpotModel() : base(null) {
        _occupiedProperty = new ReliableProperty<bool>(1, _occupied);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _occupiedProperty.UnsubscribeCallback();
    }
    
    private void FireOccupiedDidChange(bool value) {
        try {
            occupiedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _occupiedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _occupiedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Occupied: {
                    changed = _occupiedProperty.Read(stream, context);
                    if (changed) FireOccupiedDidChange(occupied);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _occupied = occupied;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
