using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class UserMenuDictionaryModel
{   
    //Lower Priority Variables
    [RealtimeProperty(1, false, true)]
    private RealtimeDictionary<UserMenuModel> _usersMenuData;
    
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class UserMenuDictionaryModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<UserMenuModel> usersMenuData {
        get => _usersMenuData;
    }
    
    public enum PropertyID : uint {
        UsersMenuData = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<UserMenuModel>> _usersMenuDataProperty;
    
    #endregion
    
    public UserMenuDictionaryModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _usersMenuData = new Normal.Realtime.Serialization.RealtimeDictionary<UserMenuModel>();
        childModels[0] = _usersMenuData;
        
        SetChildren(childModels);
        
        _usersMenuDataProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<UserMenuModel>>(1, _usersMenuData);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _usersMenuDataProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _usersMenuDataProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.UsersMenuData: {
                    changed = _usersMenuDataProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _usersMenuData = usersMenuData;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
