using Normal.Realtime.Serialization;
using System.Collections;
using UnityEngine;
using Normal.Realtime;

[RealtimeModel]
public partial class HazardListModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeArray<HazardModel> _hazards;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class HazardListModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeArray<HazardModel> hazards {
        get => _hazards;
    }
    
    public enum PropertyID : uint {
        Hazards = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeArray<HazardModel>> _hazardsProperty;
    
    #endregion
    
    public HazardListModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _hazards = new Normal.Realtime.Serialization.RealtimeArray<HazardModel>();
        childModels[0] = _hazards;
        
        SetChildren(childModels);
        
        _hazardsProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeArray<HazardModel>>(1, _hazards);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _hazardsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _hazardsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Hazards: {
                    changed = _hazardsProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _hazards = hazards;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
